name: Acquire Unity Activation File (.alf)

on:
  workflow_dispatch:

jobs:
  acquire_alf:
    name: Acquire .alf file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v2
        id: get_alf
        with:
          unityVersion: 6000.3.4f1

      - name: Upload .alf as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: ${{ steps.get_alf.outputs.filePath }}
